services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webte2_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql

  nginx:
    image: nginx:1.27-alpine
    container_name: webte2_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  mysql:
    image: mysql:8.4
    container_name: webte2_mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: webte2_final
      MYSQL_USER: webte2
      MYSQL_PASSWORD: webte2
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
